---
name: arcane

services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:v1.15.3
    container_name: arcane
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/apps/arcane:/app/data
      - /data/stacks:/opt/stacks
    environment:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
      APP_URL: arcane.pipusznicy.cloud
      PORT: 3000
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      PROJECTS_DIRECTORY: /opt/stacks
      DISK_USAGE_PATH: /data
    ports:
      - "0.0.0.0:8085:3000"
    networks:
      - caddy
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 10 --silent --show-error --fail http://localhost:3000/ || exit 1
    labels:
      # Caddy reverse proxy
      caddy_0: arcane.pipusznicy.cloud
      caddy_0.tls: ${ACME_TLS_CERT} ${ACME_TLS_KEY}
      caddy_0.reverse_proxy: "{{upstreams 3000}}"
      caddy_1: arcane.home arcane.pipusznicy
      caddy_1.tls: internal
      caddy_1.reverse_proxy: "{{upstreams 3000}}"
      # LoggiFly
      loggifly.monitor: "true"
      loggifly.excluded_keywords: "errors=\\d+"
      # Homepage service discovery
      homepage.group: Infrastructure
      homepage.name: Arcane
      homepage.icon: arcane.png
      homepage.href: https://arcane.pipusznicy.cloud
      homepage.description: Docker Manager
      homepage.weight: 20

networks:
  caddy:
    external: true
