---
name: headscale

services:
  headplane:
    image: ghcr.io/tale/headplane:0.6.2
    container_name: headplane
    volumes:
      - /data/apps/headscale/headplane/config.yaml:/etc/headplane/config.yaml:ro
      - /data/apps/headscale/headplane-data:/var/lib/headplane
      - /data/apps/headscale/config:/etc/headscale:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dokploy-network
    restart: unless-stopped

  headscale:
    image: ghcr.io/juanfont/headscale:0.28.0
    container_name: headscale
    volumes:
      - /data/apps/headscale/config:/etc/headscale
      - /data/apps/headscale/data:/var/lib/headscale
    labels:
      - "me.tale.headplane.target=headscale"
    networks:
      - dokploy-network
    command: headscale serve
    restart: unless-stopped

  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.94.2
    container_name: tailscale
    hostname: zapp
    volumes:
      - /data/apps/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=zapp
      - TS_EXTRA_ARGS=--login-server=https://headscale.pawelad.me
    network_mode: "host"
    restart: unless-stopped
    cap_add:
      - net_admin
      - sys_module

networks:
  dokploy-network:
    external: true
