---
name: headscale

services:
  headplane:
    image: ghcr.io/tale/headplane:0.6.2
    container_name: headplane
    volumes:
      - /data/apps/headscale/headplane/config.yaml:/etc/headplane/config.yaml:ro
      - /data/apps/headscale/headplane-data:/var/lib/headplane
      - /data/apps/headscale/config:/etc/headscale:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headplane.rule=Host(`${HEADPLANE_HOSTNAME}`)"
      - "traefik.http.routers.headplane.entrypoints=websecure"
      - "traefik.http.routers.headplane.tls.certresolver=letsencrypt"
      - "traefik.http.services.headplane.loadbalancer.server.port=3000"

  headscale:
    image: ghcr.io/juanfont/headscale:0.28.0
    container_name: headscale
    volumes:
      - /data/apps/headscale/config:/etc/headscale
      - /data/apps/headscale/data:/var/lib/headscale
    networks:
      - dokploy-network
    command: serve
    restart: unless-stopped
    labels:
      - "me.tale.headplane.target=headscale"
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`${HEADSCALE_HOSTNAME}`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls.certresolver=letsencrypt"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"

networks:
  dokploy-network:
    external: true
