---
- name: "Create dokploy network"
  community.docker.docker_network:
    name: dokploy-network

- name: "Ensure Dokploy stack is up to date"
  ansible.builtin.import_tasks: ../../../tasks/ensure_stack.yml
  vars:
    stack_name: dokploy
