---
- name: "Ensure Rathole configuration directory exists"
  ansible.builtin.file:
    path: "{{ apps_data_dir }}/rathole"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "0755"

- name: "Ensure Rathole server configuration"
  ansible.builtin.import_tasks: ../../../tasks/ensure_config.yml
  vars:
    service_name: "rathole"
    config_src: "server.toml.j2"
    config_dest: "{{ apps_data_dir }}/rathole/server.toml"
    mode: "0640"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"

- name: "Ensure Rathole stack is up to date"
  ansible.builtin.import_tasks: ../../../tasks/ensure_stack.yml
  vars:
    stack_name: routing
