---
name: dokploy

services:
  dokploy:
    image: dokploy/dokploy:v0.28.2
    container_name: dokploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/app/dokploy:/app/data
    environment:
      PORT: 3000
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:3000:3000"
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    name: dokploy-network
    external: true
