---
name: stirling-pdf

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:2.4.6
    container_name: stirling-pdf
    volumes:
      - /data/apps/stirling-pdf/configs:/configs
      - /data/apps/stirling-pdf/logs:/logs
      - /data/apps/stirling-pdf/pipeline:/pipeline
      - /data/apps/stirling-pdf/tessdata:/usr/share/tessdata
    environment:
      MODE: "BOTH"
      SECURITY_ENABLELOGIN: "false"
      LANGS: "en_GB"
    ports:
      - "0.0.0.0:8088:8080"
    networks:
      - caddy
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
    labels:
      # Caddy reverse proxy
      caddy_0: pdf.pipusznicy.cloud
      caddy_0.tls: ${ACME_TLS_CERT} ${ACME_TLS_KEY}
      caddy_0.reverse_proxy: "{{upstreams 8080}}"
      caddy_1: pdf.home pdf.pipusznicy
      caddy_1.tls: internal
      caddy_1.reverse_proxy: "{{upstreams 8080}}"
      # LoggiFly
      loggifly.monitor: "true"
      loggifly.excluded_keywords: "System resource status changed"
      # Homepage service discovery
      homepage.group: Apps
      homepage.name: Stirling PDF
      homepage.icon: stirling-pdf.png
      homepage.href: https://pdf.pipusznicy.cloud
      homepage.description: PDF Manipulation Tools
      homepage.weight: 50

networks:
  caddy:
    external: true
