---
- name: "Restart Bluetooth"
  ansible.builtin.systemd:
    daemon_reload: true
    name: bluetooth
    state: restarted

- name: "Restart systemd-resolved"
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
