---
name: monitoring

services:
  beszel-agent:
    image: henrygd/beszel-agent:0.9.1
    container_name: beszel-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: ${BESZEL_AGENT_KEY}
    network_mode: host
    restart: unless-stopped

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:1.15.5
    container_name: komodo-periphery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - KOMODO_PERIPHERY_PORT=8120
    network_mode: host
    restart: unless-stopped
