---
name: yamtrack

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: yamtrack-redis
    volumes:
      - /data/apps/yamtrack/redis:/data
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack:0.25.2
    container_name: yamtrack
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - /data/apps/yamtrack:/app/db
    environment:
      SECRET: ${YAMTRACK_SECRET}
      REDIS_URL: redis://yamtrack-redis:6379
    networks:
      - caddy
      - internal
    restart: unless-stopped
    healthcheck:
      test: wget -qO- http://127.0.0.1:8000/health/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      # Caddy reverse proxy
      caddy_0: ${YAMTRACK_URL}
      caddy_0.tls: ${ACME_TLS_CERT} ${ACME_TLS_KEY}
      caddy_0.reverse_proxy: "{{upstreams 8000}}"
      caddy_1: yamtrack.home yamtrack.pipusznicy
      caddy_1.tls: internal
      caddy_1.reverse_proxy: "{{upstreams 8000}}"
      # LoggiFly
      loggifly.monitor: "true"
      # Homepage service discovery
      homepage.group: Apps
      homepage.name: YamTrack
      homepage.icon: yamtrack.png
      homepage.href: ${YAMTRACK_URL}
      homepage.description: Media Tracker

networks:
  caddy:
    external: true
  internal:
    internal: true
