// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"
)

type Episode struct {
	ID               int64     `json:"id"`
	EpisodeNumber    int64     `json:"episode_number"`
	ProgrammeID      int64     `json:"programme_id"`
	Title            string    `json:"title"`
	Description      string    `json:"description"`
	WebUrl           string    `json:"web_url"`
	ImageUrl         string    `json:"image_url"`
	Since            time.Time `json:"since"`
	Till             time.Time `json:"till"`
	RecordingStarted time.Time `json:"recording_started"`
	DurationSeconds  int64     `json:"duration_seconds"`
	Year             int64     `json:"year"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
}
