// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"time"
)

const getActiveRecordings = `-- name: GetActiveRecordings :many
SELECT id, episode_number, programme_id, title, description, web_url, image_url, since, till, recording_started, duration_seconds, year, status, created_at FROM episodes
WHERE status = 'recording'
ORDER BY episode_number ASC
`

func (q *Queries) GetActiveRecordings(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getActiveRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeNumber,
			&i.ProgrammeID,
			&i.Title,
			&i.Description,
			&i.WebUrl,
			&i.ImageUrl,
			&i.Since,
			&i.Till,
			&i.RecordingStarted,
			&i.DurationSeconds,
			&i.Year,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, episode_number, programme_id, title, description, web_url, image_url, since, till, recording_started, duration_seconds, year, status, created_at FROM episodes
WHERE episode_number = ? LIMIT 1
`

func (q *Queries) GetEpisode(ctx context.Context, episodeNumber int64) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisode, episodeNumber)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.EpisodeNumber,
		&i.ProgrammeID,
		&i.Title,
		&i.Description,
		&i.WebUrl,
		&i.ImageUrl,
		&i.Since,
		&i.Till,
		&i.RecordingStarted,
		&i.DurationSeconds,
		&i.Year,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodes = `-- name: GetEpisodes :many
SELECT id, episode_number, programme_id, title, description, web_url, image_url, since, till, recording_started, duration_seconds, year, status, created_at FROM episodes
ORDER BY episode_number DESC
LIMIT ? OFFSET ?
`

type GetEpisodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetEpisodes(ctx context.Context, arg GetEpisodesParams) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeNumber,
			&i.ProgrammeID,
			&i.Title,
			&i.Description,
			&i.WebUrl,
			&i.ImageUrl,
			&i.Since,
			&i.Till,
			&i.RecordingStarted,
			&i.DurationSeconds,
			&i.Year,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordedCount = `-- name: GetRecordedCount :one
SELECT COUNT(*) FROM episodes
`

func (q *Queries) GetRecordedCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRecordedCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateEpisodeStatus = `-- name: UpdateEpisodeStatus :exec
UPDATE episodes
SET status = ?
WHERE episode_number = ?
`

type UpdateEpisodeStatusParams struct {
	Status        string `json:"status"`
	EpisodeNumber int64  `json:"episode_number"`
}

func (q *Queries) UpdateEpisodeStatus(ctx context.Context, arg UpdateEpisodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeStatus, arg.Status, arg.EpisodeNumber)
	return err
}

const upsertEpisode = `-- name: UpsertEpisode :one
INSERT INTO episodes (
    episode_number,
    programme_id,
    title,
    description,
    web_url,
    image_url,
    since,
    till,
    recording_started,
    duration_seconds,
    year,
    status
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(episode_number) DO UPDATE SET
    programme_id = excluded.programme_id,
    title = excluded.title,
    description = excluded.description,
    web_url = excluded.web_url,
    image_url = excluded.image_url,
    since = excluded.since,
    till = excluded.till,
    duration_seconds = excluded.duration_seconds,
    year = excluded.year,
    status = CASE WHEN episodes.status = 'recorded' THEN 'recorded' ELSE excluded.status END
RETURNING id, episode_number, programme_id, title, description, web_url, image_url, since, till, recording_started, duration_seconds, year, status, created_at
`

type UpsertEpisodeParams struct {
	EpisodeNumber    int64     `json:"episode_number"`
	ProgrammeID      int64     `json:"programme_id"`
	Title            string    `json:"title"`
	Description      string    `json:"description"`
	WebUrl           string    `json:"web_url"`
	ImageUrl         string    `json:"image_url"`
	Since            time.Time `json:"since"`
	Till             time.Time `json:"till"`
	RecordingStarted time.Time `json:"recording_started"`
	DurationSeconds  int64     `json:"duration_seconds"`
	Year             int64     `json:"year"`
	Status           string    `json:"status"`
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, upsertEpisode,
		arg.EpisodeNumber,
		arg.ProgrammeID,
		arg.Title,
		arg.Description,
		arg.WebUrl,
		arg.ImageUrl,
		arg.Since,
		arg.Till,
		arg.RecordingStarted,
		arg.DurationSeconds,
		arg.Year,
		arg.Status,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.EpisodeNumber,
		&i.ProgrammeID,
		&i.Title,
		&i.Description,
		&i.WebUrl,
		&i.ImageUrl,
		&i.Since,
		&i.Till,
		&i.RecordingStarted,
		&i.DurationSeconds,
		&i.Year,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
