// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	GetActiveRecordings(ctx context.Context) ([]Episode, error)
	GetEpisode(ctx context.Context, episodeNumber int64) (Episode, error)
	GetEpisodes(ctx context.Context, arg GetEpisodesParams) ([]Episode, error)
	GetRecordedCount(ctx context.Context) (int64, error)
	UpdateEpisodeStatus(ctx context.Context, arg UpdateEpisodeStatusParams) error
	UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (Episode, error)
}

var _ Querier = (*Queries)(nil)
