#cloud-config
---
users:
  - default
  - name: "${username}"
    lock_passwd: true
    ssh_authorized_keys:
      - "${user_ssh_public_key}"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: "/bin/bash"

package_update: true
package_upgrade: true
package_reboot_if_required: true
