---
- Apps:
    - Mealie:
        icon: mealie.png
        href: https://mealie.pawelad.me
        description: Recipe Manager
        widget:
          type: mealie
          url: "{{HOMEPAGE_VAR_MEALIE_URL}}"
          key: "{{HOMEPAGE_VAR_MEALIE_API_KEY}}"
          version: 2
