---
title: Państwo Pipusznicy

favicon: /images/krokiet-favicon.ico

background:
  image: /images/yash-rai-JXK8dh3DKBg-unsplash.jpg
  brightness: 50
  blur: xs

headerStyle: clean
target: _blank
statusStyle: "dot"

layout:
  # home
  Home Servers:
    tab: home
    header: false
    style: row
    columns: 2

  Apps:
    tab: home
    style: column
    Apps Widgets:
      header: false
      style: row
      columns: 3
    Apps Main:
      header: false
      style: row
      columns: 4

  # lab
  Kif:
    tab: lab
    header: false
    style: column
    Kif Headscale:
      header: false
      style: row
      columns: 1
    Kif Main:
      header: false
      style: row
      columns: 2

  Zapp:
    tab: lab
    header: false
    style: column
    Zapp Headscale:
      header: false
      style: row
      columns: 1
    Zapp Main:
      header: false
      style: row
      columns: 2

  Infrastructure:
    tab: lab
    style: row
    columns: 5

  Monitoring:
    tab: lab
    style: column
    Monitoring Main:
      header: false
      style: row
      columns: 5
    Monitoring Extra:
      header: false
      style: row
      columns: 2

  Stremio:
    tab: lab
    style: row
    columns: 4
