---
- logo:
    icon: /images/krokiet.png
- openmeteo:
    label: Kraków
    latitude: 50
    longitude: 20
    timezone: Europe/Warsaw
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
