---
name: beszel

services:
  beszel:
    image: henrygd/beszel:0.18.3
    container_name: beszel
    volumes:
      - /data/apps/beszel/server:/beszel_data
      - /data/apps/beszel/socket:/beszel_socket
    ports:
      - "0.0.0.0:8090:8090"
    networks:
      - caddy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/beszel", "health", "--url", "http://127.0.0.1:8090/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    labels:
      caddy_0: beszel.pipusznicy.cloud
      caddy_0.tls: ${ACME_TLS_CERT} ${ACME_TLS_KEY}
      caddy_0.reverse_proxy: "{{upstreams 8090}}"
      caddy_0.reverse_proxy.flush_interval: -1
      caddy_1: beszel.home beszel.pipusznicy
      caddy_1.tls: internal
      caddy_1.reverse_proxy: "{{upstreams 8090}}"
      caddy_1.reverse_proxy.flush_interval: -1
  beszel-agent:
    image: henrygd/beszel-agent:0.18.3
    container_name: beszel-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/apps/beszel/agent:/var/lib/beszel-agent
      - /data/apps/beszel/socket:/beszel_socket
      - /data/.beszel:/extra-filesystems/sdb1__Media:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/agent", "health" ]

networks:
  caddy:
    external: true
