---
- name: "Ensure Beszel stack is up to date"
  ansible.builtin.import_role:
    name: common
    tasks_from: ensure_stack
  vars:
    stack_name: beszel
    env_template: "{{ inventory_hostname }}/beszel.env.j2"
