---
- name: "Ensure ntfy data directory for config exists"
  ansible.builtin.file:
    path: "{{ apps_data_dir }}/ntfy/config"
    state: directory
    mode: "0755"

- name: "Ensure ntfy configuration"
  ansible.builtin.import_role:
    name: common
    tasks_from: ensure_config
  vars:
    service_name: "ntfy"
    config_src: "{{ inventory_hostname }}/ntfy.server.yml.j2"
    config_dest: "{{ apps_data_dir }}/ntfy/config/server.yml"
    mode: "0644"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"

- name: "Ensure ntfy stack is up to date"
  ansible.builtin.import_role:
    name: common
    tasks_from: ensure_stack
  vars:
    stack_name: ntfy
