---
- name: "Ensure Ollama stack is up to date"
  ansible.builtin.import_role:
    name: common
    tasks_from: ensure_stack
  vars:
    stack_name: ollama
    env_template: "{{ inventory_hostname }}/ollama.env.j2"

- name: "Wait for Ollama container to be healthy"
  community.docker.docker_container_info:
    name: ollama
  register: stacks_ollama_check
  ignore_errors: true
  retries: 10
  delay: 5
  until: >-
    stacks_ollama_check.container is defined
    and stacks_ollama_check.container.State.Health.Status is defined
    and stacks_ollama_check.container.State.Health.Status == 'healthy'

- name: "Get list of installed Ollama models"
  community.docker.docker_container_exec:
    container: ollama
    command: ollama list
  register: stacks_ollama_list
  when: not stacks_ollama_check.failed | default(false)
  changed_when: false

- name: "Pull required Ollama models"
  community.docker.docker_container_exec:
    container: ollama
    command: "ollama pull {{ item }}"
  register: stacks_ollama_pull
  changed_when: "'already up to date' not in stacks_ollama_pull.stdout and 'success' in stacks_ollama_pull.stdout"
  when: not stacks_ollama_check.failed | default(false)
  loop: "{{ kif_llm_models | default([]) }}"

- name: "Extract names of currently installed models"
  ansible.builtin.set_fact:
    installed_ollama_models: >-
      {{
        stacks_ollama_list.stdout_lines[1:] | default([])
        | select('match', '^\\S+')
        | map('split')
        | map('first')
        | list
      }}
  when: not stacks_ollama_check.failed | default(false)
