---
name: mealie

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.17.0
    container_name: mealie
    volumes:
      - /data/apps/mealie:/app/data
    environment:
      DB_ENGINE: sqlite
      BASE_URL: ${MEALIE_URL}
      ALLOW_SIGNUP: false
    networks:
      - caddy
    restart: unless-stopped
    healthcheck:
      test: curl -f http://127.0.0.1:9000/api/app/about || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      caddy_0: mealie.pipusznicy.cloud
      caddy_0.tls: ${ACME_TLS_CERT} ${ACME_TLS_KEY}
      caddy_0.reverse_proxy: "{{upstreams 9000}}"
      caddy_1: mealie.home mealie.pipusznicy
      caddy_1.tls: internal
      caddy_1.reverse_proxy: "{{upstreams 9000}}"
      # LoggiFly
      loggifly.monitor: "true"
networks:
  caddy:
    external: true
