---
# Zapp Server Provisioning Playbook

- name: "Setup Zapp Server"
  hosts: zapp
  become: true

  roles:
    # Configure server
    - role: common
      tags: common
    # Install Docker
    - role: docker
      tags: docker
    # Create the Git deployment hook for the repository
    - role: git_deploy
      tags: git_deploy
