---
name: rathole

services:
  rathole:
    ports:
      - "0.0.0.0:2333:2333" # Client connection port (binds to VPS public IP)
    networks:
      - dokploy-network
    labels:
      traefik.enable: true
      traefik.http.routers.rathole-aiostreams.rule: Host(`stremio.pawelad.me`)
      traefik.http.routers.rathole-aiostreams.entrypoints: websecure
      traefik.http.routers.rathole-aiostreams.tls.certresolver: letsencrypt
      traefik.http.services.rathole-aiostreams.loadbalancer.server.port: 3030
    extends:
      file: ../../common/rathole/base.yaml
      service: rathole-base

networks:
  dokploy-network:
    external: true
